### ISSUE TITLE
perhaps useless brackets 

### ISSUE THREAD

**Issue by devkgs** [jmmourier/laughing-couscous#3]
In Hali.h, line 16,
    virtual int getBatteryVoltage() {};

Why are { and } prensent?

Best wishes

**Comment by jmmourier** [comment]
definitly useless, it's a residu when Hali was not the interface but the HalReal implementation, I will remove it next time.

**Comment by jmmourier** [comment]
fixed

**Comment by jmmourier** [comment]
Fixed
