### ISSUE TITLE
encoder goes negative in forward and backward

### ISSUE THREAD

**Issue by devkgs** [jmmourier/laughing-couscous#58]
[RobotController]robot controller callback onClientRequestSetSpeed1 1
encoder1:0 encoder2:0 posX:1 posY:1 angle:0
encoder1:-44 encoder2:-44 posX:0.923206 posY:1 angle:0
encoder1:-170 encoder2:-170 posX:0.703294 posY:1 angle:0

same when speed is -1, -1

**Comment by jmmourier** [comment]
Let me check that on the real robot and I fix it

**Comment by devkgs** [comment]
Question about arguments of setMd25Speed.

 setMd25Speed(speed_1, speed_2) : 
- stop=127
- forward= values>127
- backward= values < 127

?
